language: zh

#pipeline:
#- name: "JiebaTokenizer"
#- name: "RegexFeaturizer"
#- name: "CRFEntityExtractor"
#- name: "EntitySynonymMapper"
#- name: "CountVectorsFeaturizer"
#- name: "CountVectorsFeaturizer"
#  token_pattern: (?u)\b\w+\b
#  analyzer: "char_wb"
#  min_ngram: 1
#  max_ngram: 4
#- name: "EmbeddingIntentClassifier"
pipeline:
- name: "nlp_mitie"
  model: "data/total_word_feature_extractor_zh.dat"
- name: "tokenizer_jieba"
- name: "ner_mitie"
- name: "ner_synonyms"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_mitie"
- name: "intent_classifier_sklearn"

policies:
  - name: FallbackPolicy
  - name: MemoizationPolicy
  - name: FormPolicy
  - name: MappingPolicy
